"""
--------------------------------------------------
data_pipeline/seed_data.py — Comprehensive Hospital & Procedure Dataset
--------------------------------------------------

Generates 60+ accredited hospitals across Chandigarh Tricity, Punjab,
Haryana, Delhi NCR, with 35+ PMJAY 2.2-aligned procedure packages,
realistic ICU telemetry, multi-specialty facilities, departments, and reviews.
"""

import asyncio
import structlog
import random
from typing import Optional

logger = structlog.get_logger()

# --------------------------------------------------
# 60+ Hospitals Dataset
# --------------------------------------------------
HOSPITALS_DATA = [
    # ── Chandigarh Tricity: Chandigarh ──
    {
        "name": "PGIMER Chandigarh",
        "type": "government",
        "address": "Sector 12, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160012",
        "latitude": 30.7650,
        "longitude": 76.7810,
        "phone": "0172-2755555",
        "emergency_phone": "0172-2756565",
        "beds_total": 1948,
        "beds_icu": 220,
        "beds_icu_available": 14,
        "beds_emergency": 120,
        "beds_general": 1608,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1962,
        "total_doctors": 520,
        "description": "Post Graduate Institute of Medical Education and Research — India's premier apex research and medical institute. Provides tertiary emergency, cardiac, and organ transplant services.",
    },
    {
        "name": "Government Medical College & Hospital (GMCH-32)",
        "type": "government",
        "address": "Sector 32, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160030",
        "latitude": 30.7128,
        "longitude": 76.7880,
        "phone": "0172-2665253",
        "emergency_phone": "0172-2665254",
        "beds_total": 1100,
        "beds_icu": 95,
        "beds_icu_available": 9,
        "beds_emergency": 70,
        "beds_general": 935,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1981,
        "total_doctors": 310,
        "description": "GMCH Chandigarh — premier tertiary medical college and teaching hospital with round-the-clock emergency and trauma critical care.",
    },
    {
        "name": "Government Multi Specialty Hospital (GMSH-16)",
        "type": "government",
        "address": "Sector 16, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160016",
        "latitude": 30.7485,
        "longitude": 76.7794,
        "phone": "0172-2761616",
        "emergency_phone": "0172-2761616",
        "beds_total": 500,
        "beds_icu": 40,
        "beds_icu_available": 6,
        "beds_emergency": 50,
        "beds_general": 410,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1952,
        "total_doctors": 180,
        "description": "Historic civil multi-specialty government hospital serving downtown Chandigarh with active maternal, neonatal, and emergency services.",
    },
    {
        "name": "Mukat Hospital & Heart Institute",
        "type": "private",
        "address": "Sector 34-A, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160022",
        "latitude": 30.7224,
        "longitude": 76.7681,
        "phone": "0172-4344444",
        "emergency_phone": "0172-4344400",
        "beds_total": 120,
        "beds_icu": 24,
        "beds_icu_available": 5,
        "beds_emergency": 15,
        "beds_general": 81,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1994,
        "total_doctors": 85,
        "description": "Pioneering private cardiac and critical care facility with established catheterization labs and interventional cardiology.",
    },
    {
        "name": "Healing Hospital",
        "type": "private",
        "address": "Sector 34-A, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160022",
        "latitude": 30.7210,
        "longitude": 76.7695,
        "phone": "0172-5000000",
        "emergency_phone": "0172-5000001",
        "beds_total": 100,
        "beds_icu": 20,
        "beds_icu_available": 4,
        "beds_emergency": 12,
        "beds_general": 68,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2014,
        "total_doctors": 65,
        "description": "Boutique multi-specialty center specializing in minimally invasive spine, orthopedics, and laparoscopy.",
    },
    {
        "name": "Eden Critical Care Hospital",
        "type": "private",
        "address": "Industrial Area Phase I, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160002",
        "latitude": 30.7071,
        "longitude": 76.7978,
        "phone": "0172-5272727",
        "emergency_phone": "0172-5272700",
        "beds_total": 90,
        "beds_icu": 28,
        "beds_icu_available": 5,
        "beds_emergency": 16,
        "beds_general": 46,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2015,
        "total_doctors": 55,
        "description": "Dedicated tertiary critical care, neuro-trauma, and ventilator resuscitation hospital in Chandigarh.",
    },
    {
        "name": "Landmark Hospital",
        "type": "private",
        "address": "Sector 33-C, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160020",
        "latitude": 30.7188,
        "longitude": 76.7725,
        "phone": "0172-4022222",
        "emergency_phone": "0172-4022200",
        "beds_total": 75,
        "beds_icu": 15,
        "beds_icu_available": 3,
        "beds_emergency": 10,
        "beds_general": 50,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2005,
        "total_doctors": 45,
        "description": "Specialized orthopedic, joint replacement, and arthroscopy center serving Tricity patients.",
    },
    {
        "name": "Chaitanya Hospital",
        "type": "private",
        "address": "Sector 44-C, Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pincode": "160044",
        "latitude": 30.7088,
        "longitude": 76.7582,
        "phone": "0172-5088088",
        "emergency_phone": "0172-5088000",
        "beds_total": 80,
        "beds_icu": 22,
        "beds_icu_available": 6,
        "beds_emergency": 10,
        "beds_general": 48,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2009,
        "total_doctors": 40,
        "description": "Premier pediatric and neonatal critical care (NICU/PICU) facility with specialized maternity services.",
    },

    # ── Chandigarh Tricity: Mohali / SAS Nagar ──
    {
        "name": "Fortis Hospital Mohali",
        "type": "private",
        "address": "Sector 62, Phase 8, SAS Nagar, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160062",
        "latitude": 30.7047,
        "longitude": 76.7179,
        "phone": "0172-4692222",
        "emergency_phone": "0172-4692200",
        "beds_total": 355,
        "beds_icu": 68,
        "beds_icu_available": 9,
        "beds_emergency": 35,
        "beds_general": 252,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "NABH & JCI",
        "established_year": 2001,
        "total_doctors": 240,
        "description": "Flagship JCI-accredited tertiary care multi-specialty hospital celebrated for cardiology, oncology, and robotic joint surgery.",
    },
    {
        "name": "Max Super Speciality Hospital Mohali",
        "type": "private",
        "address": "Block B, Phase VI, SAS Nagar, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160055",
        "latitude": 30.7271,
        "longitude": 76.7193,
        "phone": "0172-6652000",
        "emergency_phone": "0172-6652100",
        "beds_total": 280,
        "beds_icu": 52,
        "beds_icu_available": 6,
        "beds_emergency": 30,
        "beds_general": 198,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH & JCI",
        "established_year": 2012,
        "total_doctors": 190,
        "description": "Comprehensive quaternary care institute with 24/7 primary angioplasty, neurosciences, and bone marrow transplant units.",
    },
    {
        "name": "Ivy Hospital Mohali",
        "type": "private",
        "address": "Sector 71, SAS Nagar, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160071",
        "latitude": 30.6894,
        "longitude": 76.7291,
        "phone": "0172-5212000",
        "emergency_phone": "0172-5212100",
        "beds_total": 220,
        "beds_icu": 38,
        "beds_icu_available": 7,
        "beds_emergency": 25,
        "beds_general": 157,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2008,
        "total_doctors": 140,
        "description": "NABH-accredited super-specialty hospital with wide Ayushman PMJAY cashless coverage and advanced oncology/dialysis care.",
    },
    {
        "name": "Sohana Multi Speciality Hospital",
        "type": "trust",
        "address": "Sector 77, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160077",
        "latitude": 30.6725,
        "longitude": 76.7121,
        "phone": "0172-5044444",
        "emergency_phone": "0172-5044400",
        "beds_total": 350,
        "beds_icu": 45,
        "beds_icu_available": 8,
        "beds_emergency": 30,
        "beds_general": 275,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1995,
        "total_doctors": 160,
        "description": "Charitable trust super-specialty institution renowned for eye surgery, cancer care, and highly subsidized cardiac procedures.",
    },
    {
        "name": "Indus Super Speciality Hospital",
        "type": "private",
        "address": "Opposite DC Office, Phase 1, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160055",
        "latitude": 30.7312,
        "longitude": 76.7265,
        "phone": "0172-5099999",
        "emergency_phone": "0172-5099900",
        "beds_total": 150,
        "beds_icu": 28,
        "beds_icu_available": 5,
        "beds_emergency": 20,
        "beds_general": 102,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2002,
        "total_doctors": 90,
        "description": "Established community hospital delivering accessible dialysis, trauma resuscitation, and general surgery.",
    },
    {
        "name": "Shalby Multi-Specialty Hospital Mohali",
        "type": "private",
        "address": "Phase 9, Sector 63, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160062",
        "latitude": 30.6974,
        "longitude": 76.7381,
        "phone": "0172-4388888",
        "emergency_phone": "0172-4388800",
        "beds_total": 145,
        "beds_icu": 25,
        "beds_icu_available": 4,
        "beds_emergency": 15,
        "beds_general": 105,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2017,
        "total_doctors": 75,
        "description": "Center of excellence for zero-technique knee replacements, orthopedic rehabilitation, and cardiac diagnostics.",
    },
    {
        "name": "Mayo Healthcare Super Speciality Hospital",
        "type": "private",
        "address": "Sector 69, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160062",
        "latitude": 30.6948,
        "longitude": 76.7118,
        "phone": "0172-5092000",
        "emergency_phone": "0172-5092100",
        "beds_total": 180,
        "beds_icu": 32,
        "beds_icu_available": 6,
        "beds_emergency": 20,
        "beds_general": 128,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2011,
        "total_doctors": 110,
        "description": "Multi-specialty center with advanced laparoscopic, cardiac cath lab, and critical care units.",
    },
    {
        "name": "Cheema Medical Complex",
        "type": "private",
        "address": "Near Telephone Exchange, Phase 4, Mohali",
        "city": "Mohali",
        "state": "Punjab",
        "pincode": "160059",
        "latitude": 30.7180,
        "longitude": 76.7210,
        "phone": "0172-2270077",
        "emergency_phone": "0172-2270078",
        "beds_total": 70,
        "beds_icu": 14,
        "beds_icu_available": 3,
        "beds_emergency": 10,
        "beds_general": 46,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1988,
        "total_doctors": 35,
        "description": "Long-standing surgical and trauma nursing home providing rapid inpatient emergency triage in SAS Nagar.",
    },

    # ── Chandigarh Tricity: Panchkula ──
    {
        "name": "Alchemist Hospital Panchkula",
        "type": "private",
        "address": "Sector 21, Panchkula",
        "city": "Panchkula",
        "state": "Haryana",
        "pincode": "134109",
        "latitude": 30.6961,
        "longitude": 76.8600,
        "phone": "0172-2570000",
        "emergency_phone": "0172-2570100",
        "beds_total": 175,
        "beds_icu": 32,
        "beds_icu_available": 5,
        "beds_emergency": 20,
        "beds_general": 123,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2010,
        "total_doctors": 115,
        "description": "NABH-accredited tertiary hospital serving northern Haryana with advanced cardiac, neurology, and gastroenterology facilities.",
    },
    {
        "name": "Civil Hospital Sector 6 Panchkula",
        "type": "government",
        "address": "Sector 6, Panchkula",
        "city": "Panchkula",
        "state": "Haryana",
        "pincode": "134109",
        "latitude": 30.6985,
        "longitude": 76.8594,
        "phone": "0172-2560166",
        "emergency_phone": "0172-2560166",
        "beds_total": 320,
        "beds_icu": 28,
        "beds_icu_available": 6,
        "beds_emergency": 45,
        "beds_general": 247,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1975,
        "total_doctors": 95,
        "description": "District apex public hospital equipped with modern trauma center, PMJAY helpdesk, and regional blood bank.",
    },
    {
        "name": "Paras Health Panchkula",
        "type": "private",
        "address": "Sector 22, Panchkula",
        "city": "Panchkula",
        "state": "Haryana",
        "pincode": "134109",
        "latitude": 30.6881,
        "longitude": 76.8672,
        "phone": "0172-5244444",
        "emergency_phone": "0172-5244400",
        "beds_total": 200,
        "beds_icu": 40,
        "beds_icu_available": 7,
        "beds_emergency": 25,
        "beds_general": 135,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2019,
        "total_doctors": 130,
        "description": "State-of-the-art super-specialty hospital with advanced cath labs, neuro-surgery, and clinical oncology suites.",
    },
    {
        "name": "Ojas Super Speciality Hospital",
        "type": "private",
        "address": "Sector 26, Panchkula",
        "city": "Panchkula",
        "state": "Haryana",
        "pincode": "134116",
        "latitude": 30.6795,
        "longitude": 76.8821,
        "phone": "0172-5285285",
        "emergency_phone": "0172-5285200",
        "beds_total": 210,
        "beds_icu": 42,
        "beds_icu_available": 8,
        "beds_emergency": 25,
        "beds_general": 143,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2018,
        "total_doctors": 125,
        "description": "Alchemist group quaternary care facility specialized in organ transplants, liver ICU, and emergency cardiology.",
    },
    {
        "name": "Dhawan Hospital",
        "type": "private",
        "address": "Sector 7, Panchkula",
        "city": "Panchkula",
        "state": "Haryana",
        "pincode": "134109",
        "latitude": 30.7020,
        "longitude": 76.8510,
        "phone": "0172-2598888",
        "emergency_phone": "0172-2598800",
        "beds_total": 60,
        "beds_icu": 12,
        "beds_icu_available": 3,
        "beds_emergency": 8,
        "beds_general": 40,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1998,
        "total_doctors": 30,
        "description": "Respected family surgical and medical center offering laparoscopy, urology, and maternity packages.",
    },

    # ── Punjab: Ludhiana ──
    {
        "name": "Christian Medical College (CMC) Ludhiana",
        "type": "trust",
        "address": "Brown Road, Ludhiana",
        "city": "Ludhiana",
        "state": "Punjab",
        "pincode": "141008",
        "latitude": 30.9109,
        "longitude": 75.8320,
        "phone": "0161-2302000",
        "emergency_phone": "0161-2302100",
        "beds_total": 850,
        "beds_icu": 95,
        "beds_icu_available": 12,
        "beds_emergency": 65,
        "beds_general": 690,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1894,
        "total_doctors": 340,
        "description": "One of India's oldest apex missionary medical institutions, offering subsidized tertiary care, trauma centers, and advanced neurology.",
    },
    {
        "name": "Dayanand Medical College & Hospital (DMCH)",
        "type": "trust",
        "address": "Civil Lines, Tagore Nagar, Ludhiana",
        "city": "Ludhiana",
        "state": "Punjab",
        "pincode": "141001",
        "latitude": 30.9011,
        "longitude": 75.8573,
        "phone": "0161-4687700",
        "emergency_phone": "0161-4687777",
        "beds_total": 1350,
        "beds_icu": 140,
        "beds_icu_available": 16,
        "beds_emergency": 90,
        "beds_general": 1120,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1934,
        "total_doctors": 420,
        "description": "Premier medical college and apex tertiary hospital with dedicated Hero DMC Heart Institute and kidney transplant programs.",
    },
    {
        "name": "SPS Apollo Hospitals Ludhiana",
        "type": "private",
        "address": "Grand Trunk Road, Sherpur Chowk, Ludhiana",
        "city": "Ludhiana",
        "state": "Punjab",
        "pincode": "141003",
        "latitude": 30.8944,
        "longitude": 75.7968,
        "phone": "0161-6770000",
        "emergency_phone": "0161-6770100",
        "beds_total": 350,
        "beds_icu": 58,
        "beds_icu_available": 8,
        "beds_emergency": 40,
        "beds_general": 252,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "JCI & NABH",
        "established_year": 2005,
        "total_doctors": 210,
        "description": "Satguru Partap Singh Apollo Hospital — JCI-accredited cardiac, joint reconstruction, and surgical oncology destination.",
    },
    {
        "name": "Fortis Hospital Ludhiana",
        "type": "private",
        "address": "Chandigarh Road, Near Jamalpur, Ludhiana",
        "city": "Ludhiana",
        "state": "Punjab",
        "pincode": "141010",
        "latitude": 30.9054,
        "longitude": 75.9122,
        "phone": "0161-5225555",
        "emergency_phone": "0161-5225500",
        "beds_total": 260,
        "beds_icu": 48,
        "beds_icu_available": 7,
        "beds_emergency": 30,
        "beds_general": 182,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2014,
        "total_doctors": 160,
        "description": "Multi-specialty hospital with advanced emergency trauma units, interventional cath lab, and medical oncology.",
    },
    {
        "name": "Mohan Dai Oswal Cancer Hospital",
        "type": "trust",
        "address": "GT Road, Sherpur Bypass, Ludhiana",
        "city": "Ludhiana",
        "state": "Punjab",
        "pincode": "141009",
        "latitude": 30.8875,
        "longitude": 75.8920,
        "phone": "0161-2676100",
        "emergency_phone": "0161-2676101",
        "beds_total": 300,
        "beds_icu": 35,
        "beds_icu_available": 5,
        "beds_emergency": 25,
        "beds_general": 240,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1984,
        "total_doctors": 120,
        "description": "Charitable cancer specialty institute providing radiotherapy (LINAC), chemotherapy, and surgical oncology with PMJAY cashless access.",
    },
    {
        "name": "Deep Hospital Ludhiana",
        "type": "private",
        "address": "Model Town, Ludhiana",
        "city": "Ludhiana",
        "state": "Punjab",
        "pincode": "141002",
        "latitude": 30.8860,
        "longitude": 75.8450,
        "phone": "0161-5034444",
        "emergency_phone": "0161-5034400",
        "beds_total": 130,
        "beds_icu": 24,
        "beds_icu_available": 4,
        "beds_emergency": 15,
        "beds_general": 91,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1999,
        "total_doctors": 70,
        "description": "Specialized pediatric, neonatal, and general laparoscopic hospital serving central Ludhiana.",
    },

    # ── Punjab: Amritsar ──
    {
        "name": "Government Medical College Amritsar",
        "type": "government",
        "address": "Majitha Road, Amritsar",
        "city": "Amritsar",
        "state": "Punjab",
        "pincode": "143001",
        "latitude": 31.6340,
        "longitude": 74.8723,
        "phone": "0183-2424000",
        "emergency_phone": "0183-2424001",
        "beds_total": 950,
        "beds_icu": 70,
        "beds_icu_available": 9,
        "beds_emergency": 75,
        "beds_general": 805,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1953,
        "total_doctors": 280,
        "description": "Major public medical college hospital serving northern Punjab with high-volume trauma and emergency acute care.",
    },
    {
        "name": "Fortis Escorts Hospital Amritsar",
        "type": "private",
        "address": "Majitha-Verka Bypass, Amritsar",
        "city": "Amritsar",
        "state": "Punjab",
        "pincode": "143004",
        "latitude": 31.6711,
        "longitude": 74.8820,
        "phone": "0183-5080000",
        "emergency_phone": "0183-5080001",
        "beds_total": 180,
        "beds_icu": 35,
        "beds_icu_available": 6,
        "beds_emergency": 25,
        "beds_general": 120,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "NABH",
        "established_year": 2008,
        "total_doctors": 135,
        "description": "Premier private cardiac and multi-specialty institute with advanced cath labs and minimally invasive surgery.",
    },
    {
        "name": "Amandeep Hospital Amritsar",
        "type": "private",
        "address": "Model Town, G.T. Road, Amritsar",
        "city": "Amritsar",
        "state": "Punjab",
        "pincode": "143001",
        "latitude": 31.6280,
        "longitude": 74.8620,
        "phone": "0183-5051515",
        "emergency_phone": "0183-5051500",
        "beds_total": 200,
        "beds_icu": 36,
        "beds_icu_available": 7,
        "beds_emergency": 30,
        "beds_general": 134,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1990,
        "total_doctors": 120,
        "description": "Recognized center of excellence in polytrauma management, robotic orthopedics, and plastic micro-vascular surgery.",
    },
    {
        "name": "Sri Guru Ram Das Institute of Medical Sciences",
        "type": "trust",
        "address": "Mehta Road, Vallah, Amritsar",
        "city": "Amritsar",
        "state": "Punjab",
        "pincode": "143501",
        "latitude": 31.6420,
        "longitude": 74.9230,
        "phone": "0183-2870200",
        "emergency_phone": "0183-2870201",
        "beds_total": 800,
        "beds_icu": 60,
        "beds_icu_available": 8,
        "beds_emergency": 50,
        "beds_general": 690,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1997,
        "total_doctors": 260,
        "description": "SGPC-affiliated charitable teaching hospital providing low-cost tertiary healthcare, dialysis, and surgical care.",
    },

    # ── Punjab: Jalandhar ──
    {
        "name": "Civil Hospital Jalandhar",
        "type": "government",
        "address": "Model Town Road, Jalandhar",
        "city": "Jalandhar",
        "state": "Punjab",
        "pincode": "144001",
        "latitude": 31.3260,
        "longitude": 75.5762,
        "phone": "0181-2458000",
        "emergency_phone": "0181-2458001",
        "beds_total": 720,
        "beds_icu": 45,
        "beds_icu_available": 7,
        "beds_emergency": 55,
        "beds_general": 620,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1948,
        "total_doctors": 190,
        "description": "Primary public tertiary hospital in Doaba region featuring mother & child block, trauma triage, and PMJAY desk.",
    },
    {
        "name": "Manipal Hospital Jalandhar",
        "type": "private",
        "address": "GT Road, Near Bus Stand, Jalandhar",
        "city": "Jalandhar",
        "state": "Punjab",
        "pincode": "144001",
        "latitude": 31.3280,
        "longitude": 75.5811,
        "phone": "0181-5020000",
        "emergency_phone": "0181-5020100",
        "beds_total": 230,
        "beds_icu": 40,
        "beds_icu_available": 6,
        "beds_emergency": 25,
        "beds_general": 165,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2010,
        "total_doctors": 165,
        "description": "Comprehensive multi-specialty healthcare center specializing in cardiac sciences, neurology, and kidney transplants.",
    },
    {
        "name": "Sacred Heart Hospital Jalandhar",
        "type": "trust",
        "address": "Maqsudan, GT Road, Jalandhar",
        "city": "Jalandhar",
        "state": "Punjab",
        "pincode": "144008",
        "latitude": 31.3592,
        "longitude": 75.5670,
        "phone": "0181-2670225",
        "emergency_phone": "0181-2670226",
        "beds_total": 300,
        "beds_icu": 32,
        "beds_icu_available": 5,
        "beds_emergency": 25,
        "beds_general": 243,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1978,
        "total_doctors": 110,
        "description": "Mission trust healthcare organization offering affordable surgery, obstetrics, and acute ICU care.",
    },
    {
        "name": "Patel Hospital Jalandhar",
        "type": "private",
        "address": "Civil Lines, Jalandhar",
        "city": "Jalandhar",
        "state": "Punjab",
        "pincode": "144001",
        "latitude": 31.3190,
        "longitude": 75.5850,
        "phone": "0181-5241000",
        "emergency_phone": "0181-5241001",
        "beds_total": 150,
        "beds_icu": 28,
        "beds_icu_available": 4,
        "beds_emergency": 18,
        "beds_general": 104,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1976,
        "total_doctors": 85,
        "description": "Premier cancer and surgical hospital in Doaba region featuring linear accelerator and surgical oncology.",
    },
    {
        "name": "Shrimann Superspeciality Hospital",
        "type": "private",
        "address": "Near Pathankot Bypass, Jalandhar",
        "city": "Jalandhar",
        "state": "Punjab",
        "pincode": "144012",
        "latitude": 31.3780,
        "longitude": 75.5890,
        "phone": "0181-5252525",
        "emergency_phone": "0181-5252500",
        "beds_total": 220,
        "beds_icu": 44,
        "beds_icu_available": 7,
        "beds_emergency": 30,
        "beds_general": 146,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2017,
        "total_doctors": 140,
        "description": "Ultra-modern super-specialty hospital with robotic surgery, high-end ICU, and interventional cardiology.",
    },

    # ── Punjab: Patiala & Bathinda ──
    {
        "name": "Government Rajindra Hospital Patiala",
        "type": "government",
        "address": "Rajindra Hospital Road, Patiala",
        "city": "Patiala",
        "state": "Punjab",
        "pincode": "147001",
        "latitude": 30.3498,
        "longitude": 76.3869,
        "phone": "0175-2213166",
        "emergency_phone": "0175-2213167",
        "beds_total": 1550,
        "beds_icu": 110,
        "beds_icu_available": 14,
        "beds_emergency": 85,
        "beds_general": 1355,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1950,
        "total_doctors": 320,
        "description": "Teaching hospital of Government Medical College Patiala; apex public tertiary hub for Malwa belt.",
    },
    {
        "name": "AIIMS Bathinda",
        "type": "government",
        "address": "Mandi Dabwali Road, Bathinda",
        "city": "Bathinda",
        "state": "Punjab",
        "pincode": "151001",
        "latitude": 30.1780,
        "longitude": 74.9240,
        "phone": "0164-2867250",
        "emergency_phone": "0164-2867000",
        "beds_total": 750,
        "beds_icu": 80,
        "beds_icu_available": 12,
        "beds_emergency": 60,
        "beds_general": 610,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2019,
        "total_doctors": 280,
        "description": "All India Institute of Medical Sciences Bathinda — national institute of excellence serving south-west Punjab and north Rajasthan.",
    },
    {
        "name": "Max Super Speciality Hospital Bathinda",
        "type": "private",
        "address": "Civil Lines, Near Bhagu Road, Bathinda",
        "city": "Bathinda",
        "state": "Punjab",
        "pincode": "151001",
        "latitude": 30.2012,
        "longitude": 74.9450,
        "phone": "0164-6601000",
        "emergency_phone": "0164-6601100",
        "beds_total": 200,
        "beds_icu": 35,
        "beds_icu_available": 5,
        "beds_emergency": 25,
        "beds_general": 140,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2011,
        "total_doctors": 120,
        "description": "Advanced multi-specialty private center with comprehensive oncology, cardiac cath lab, and trauma ICU.",
    },

    # ── Haryana: Ambala, Kurukshetra, Karnal, Rohtak ──
    {
        "name": "Civil Hospital Ambala City",
        "type": "government",
        "address": "Ambala City, Haryana",
        "city": "Ambala",
        "state": "Haryana",
        "pincode": "134003",
        "latitude": 30.3782,
        "longitude": 76.7767,
        "phone": "0171-2532200",
        "emergency_phone": "0171-2532201",
        "beds_total": 600,
        "beds_icu": 45,
        "beds_icu_available": 8,
        "beds_emergency": 50,
        "beds_general": 505,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1960,
        "total_doctors": 160,
        "description": "State-of-the-art government civil hospital with dedicated tertiary cardiac center and regional cancer care block.",
    },
    {
        "name": "MM Institute of Medical Sciences & Research (MMU)",
        "type": "trust",
        "address": "Mullana, Ambala",
        "city": "Ambala",
        "state": "Haryana",
        "pincode": "133207",
        "latitude": 30.2510,
        "longitude": 77.0420,
        "phone": "01731-304555",
        "emergency_phone": "01731-304500",
        "beds_total": 1050,
        "beds_icu": 90,
        "beds_icu_available": 14,
        "beds_emergency": 65,
        "beds_general": 895,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2003,
        "total_doctors": 310,
        "description": "Expansive tertiary teaching hospital with Level 1 trauma facilities, cardiac surgery, and subsidized PMJAY beds.",
    },
    {
        "name": "Kalpana Chawla Government Medical College (KCGMC)",
        "type": "government",
        "address": "Model Town, Karnal",
        "city": "Karnal",
        "state": "Haryana",
        "pincode": "132001",
        "latitude": 29.6857,
        "longitude": 76.9905,
        "phone": "0184-2266200",
        "emergency_phone": "0184-2266201",
        "beds_total": 550,
        "beds_icu": 50,
        "beds_icu_available": 7,
        "beds_emergency": 45,
        "beds_general": 455,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2017,
        "total_doctors": 210,
        "description": "Modern government medical college hospital serving the GT Road corridor with 24x7 trauma surgery.",
    },
    {
        "name": "Pt. B.D. Sharma PGIMS Rohtak",
        "type": "government",
        "address": "Medical Mor, Rohtak",
        "city": "Rohtak",
        "state": "Haryana",
        "pincode": "124001",
        "latitude": 28.8920,
        "longitude": 76.6065,
        "phone": "01262-281307",
        "emergency_phone": "01262-281300",
        "beds_total": 2100,
        "beds_icu": 180,
        "beds_icu_available": 18,
        "beds_emergency": 120,
        "beds_general": 1800,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1960,
        "total_doctors": 650,
        "description": "Haryana's premier apex state medical institution offering super-specialty surgery, transplants, and regional trauma care.",
    },

    # ── NCR: Gurugram & Faridabad ──
    {
        "name": "Medanta The Medicity Gurugram",
        "type": "private",
        "address": "Sector 38, CH Bakhtawar Singh Road, Gurugram",
        "city": "Gurugram",
        "state": "Haryana",
        "pincode": "122001",
        "latitude": 28.4395,
        "longitude": 77.0428,
        "phone": "0124-4141414",
        "emergency_phone": "0124-4141515",
        "beds_total": 1350,
        "beds_icu": 280,
        "beds_icu_available": 24,
        "beds_emergency": 120,
        "beds_general": 950,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "JCI & NABH",
        "established_year": 2009,
        "total_doctors": 680,
        "description": "Renowned multi-super-speciality medical institute housing India's top heart, liver, and multiorgan transplant programs.",
    },
    {
        "name": "Artemis Hospital Gurugram",
        "type": "private",
        "address": "Sector 51, Gurugram",
        "city": "Gurugram",
        "state": "Haryana",
        "pincode": "122001",
        "latitude": 28.4353,
        "longitude": 77.0799,
        "phone": "0124-4511111",
        "emergency_phone": "0124-4511000",
        "beds_total": 450,
        "beds_icu": 85,
        "beds_icu_available": 11,
        "beds_emergency": 50,
        "beds_general": 315,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "JCI & NABH",
        "established_year": 2007,
        "total_doctors": 340,
        "description": "First JCI & NABH accredited hospital in Gurugram, recognized for minimal invasive surgery and cardiovascular interventions.",
    },
    {
        "name": "Fortis Memorial Research Institute (FMRI)",
        "type": "private",
        "address": "Sector 44, Opposite HUDA City Centre, Gurugram",
        "city": "Gurugram",
        "state": "Haryana",
        "pincode": "122002",
        "latitude": 28.4595,
        "longitude": 77.0725,
        "phone": "0124-7160000",
        "emergency_phone": "0124-7160100",
        "beds_total": 420,
        "beds_icu": 90,
        "beds_icu_available": 10,
        "beds_emergency": 45,
        "beds_general": 285,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "JCI & NABH",
        "established_year": 2013,
        "total_doctors": 320,
        "description": "Next-generation quaternary hospital with robotic surgery, comprehensive cancer institute, and acute trauma response.",
    },
    {
        "name": "Narayana Superspeciality Hospital Gurugram",
        "type": "private",
        "address": "Plot 3201, Block - V, DLF Phase 3, Gurugram",
        "city": "Gurugram",
        "state": "Haryana",
        "pincode": "122002",
        "latitude": 28.4985,
        "longitude": 77.0982,
        "phone": "0124-6767676",
        "emergency_phone": "0124-6767600",
        "beds_total": 215,
        "beds_icu": 45,
        "beds_icu_available": 6,
        "beds_emergency": 30,
        "beds_general": 140,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2018,
        "total_doctors": 170,
        "description": "Narayana Health facility offering cost-effective complex cardiac interventions and transparent package tariffs.",
    },
    {
        "name": "Asian Institute of Medical Sciences Faridabad",
        "type": "private",
        "address": "Badkal Flyover Road, Sector 21A, Faridabad",
        "city": "Faridabad",
        "state": "Haryana",
        "pincode": "121001",
        "latitude": 28.4190,
        "longitude": 77.2980,
        "phone": "0129-4253000",
        "emergency_phone": "0129-4253100",
        "beds_total": 350,
        "beds_icu": 60,
        "beds_icu_available": 9,
        "beds_emergency": 35,
        "beds_general": 255,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2010,
        "total_doctors": 210,
        "description": "NABH and NABL accredited super-speciality hospital delivering comprehensive cancer care, neurosurgery, and PMJAY packages.",
    },
    {
        "name": "Sarvodaya Hospital Faridabad",
        "type": "private",
        "address": "Sector 8, YMCA Road, Faridabad",
        "city": "Faridabad",
        "state": "Haryana",
        "pincode": "121006",
        "latitude": 28.3750,
        "longitude": 77.3320,
        "phone": "0129-4199999",
        "emergency_phone": "0129-4199900",
        "beds_total": 300,
        "beds_icu": 50,
        "beds_icu_available": 7,
        "beds_emergency": 30,
        "beds_general": 220,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2008,
        "total_doctors": 180,
        "description": "Leading healthcare facility in south NCR with dedicated cath labs, joint replacement, and critical care units.",
    },

    # ── NCR: Delhi ──
    {
        "name": "AIIMS New Delhi",
        "type": "government",
        "address": "Sri Aurobindo Marg, Ansari Nagar, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110029",
        "latitude": 28.5672,
        "longitude": 77.2100,
        "phone": "011-26588500",
        "emergency_phone": "011-26588700",
        "beds_total": 2478,
        "beds_icu": 380,
        "beds_icu_available": 28,
        "beds_emergency": 220,
        "beds_general": 1878,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1956,
        "total_doctors": 1450,
        "description": "All India Institute of Medical Sciences — India's highest national medical apex center with world-renowned surgical and research divisions.",
    },
    {
        "name": "Safdarjung Hospital New Delhi",
        "type": "government",
        "address": "Ansari Nagar West, Ring Road, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110029",
        "latitude": 28.5665,
        "longitude": 77.2021,
        "phone": "011-26165060",
        "emergency_phone": "011-26165060",
        "beds_total": 1600,
        "beds_icu": 160,
        "beds_icu_available": 16,
        "beds_emergency": 110,
        "beds_general": 1330,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1942,
        "total_doctors": 620,
        "description": "One of India's largest central government hospitals; features premier burn unit, multi-organ ICU, and Level 1 emergency care.",
    },
    {
        "name": "Dr. Ram Manohar Lohia (RML) Hospital",
        "type": "government",
        "address": "Baba Kharak Singh Marg, Connaught Place, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110001",
        "latitude": 28.6252,
        "longitude": 77.2015,
        "phone": "011-23365525",
        "emergency_phone": "011-23365555",
        "beds_total": 1400,
        "beds_icu": 130,
        "beds_icu_available": 14,
        "beds_emergency": 90,
        "beds_general": 1180,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1932,
        "total_doctors": 540,
        "description": "Central government tertiary institution offering comprehensive cardiac surgery, stroke intervention, and acute trauma triage.",
    },
    {
        "name": "Sir Ganga Ram Hospital Delhi",
        "type": "trust",
        "address": "Rajinder Nagar, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110060",
        "latitude": 28.6385,
        "longitude": 77.1895,
        "phone": "011-25750000",
        "emergency_phone": "011-42251000",
        "beds_total": 675,
        "beds_icu": 125,
        "beds_icu_available": 15,
        "beds_emergency": 60,
        "beds_general": 490,
        "is_trauma_center": True,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 1951,
        "total_doctors": 450,
        "description": "Premier non-profit trust hospital renowned for kidney/liver transplants, minimal invasive surgery, and subsidized beds.",
    },
    {
        "name": "Indraprastha Apollo Hospital Delhi",
        "type": "private",
        "address": "Sarita Vihar, Delhi Mathura Road, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110076",
        "latitude": 28.5409,
        "longitude": 77.2879,
        "phone": "011-71791090",
        "emergency_phone": "011-71791060",
        "beds_total": 710,
        "beds_icu": 135,
        "beds_icu_available": 18,
        "beds_emergency": 75,
        "beds_general": 500,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "JCI & NABH",
        "established_year": 1996,
        "total_doctors": 480,
        "description": "First hospital in India to receive JCI accreditation; internationally renowned for complex cardiac and transplant procedures.",
    },
    {
        "name": "Max Super Speciality Hospital Saket",
        "type": "private",
        "address": "1, 2, Press Enclave Marg, Saket, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110017",
        "latitude": 28.5267,
        "longitude": 77.2147,
        "phone": "011-26515050",
        "emergency_phone": "011-26515051",
        "beds_total": 550,
        "beds_icu": 110,
        "beds_icu_available": 14,
        "beds_emergency": 65,
        "beds_general": 375,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "NABH & JCI",
        "established_year": 2006,
        "total_doctors": 410,
        "description": "Quaternary medical center housing Max Cancer Centre, cardiac sciences, neurosciences, and robotic surgical systems.",
    },
    {
        "name": "Fortis Escorts Heart Institute Okhla",
        "type": "private",
        "address": "Okhla Road, Sukhdev Vihar Metro Station, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110025",
        "latitude": 28.5609,
        "longitude": 77.2798,
        "phone": "011-47135000",
        "emergency_phone": "011-47135100",
        "beds_total": 310,
        "beds_icu": 80,
        "beds_icu_available": 11,
        "beds_emergency": 35,
        "beds_general": 195,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "JCI & NABH",
        "established_year": 1988,
        "total_doctors": 220,
        "description": "Pioneering cardiac care institution with over three decades of pediatric & adult heart transplants and electrophysiology.",
    },
    {
        "name": "BLK-Max Super Speciality Hospital",
        "type": "private",
        "address": "Pusa Road, Karol Bagh, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110005",
        "latitude": 28.6445,
        "longitude": 77.1795,
        "phone": "011-30403040",
        "emergency_phone": "011-30403000",
        "beds_total": 650,
        "beds_icu": 120,
        "beds_icu_available": 16,
        "beds_emergency": 60,
        "beds_general": 470,
        "is_trauma_center": True,
        "is_pmjay_empanelled": False,
        "accreditation": "NABH",
        "established_year": 1959,
        "total_doctors": 390,
        "description": "One of Delhi's largest private tertiary care hospitals with notable bone marrow transplant and digestive surgery units.",
    },
    {
        "name": "Institute of Liver & Biliary Sciences (ILBS)",
        "type": "government",
        "address": "D-1, Vasant Kunj, New Delhi",
        "city": "Delhi",
        "state": "Delhi",
        "pincode": "110070",
        "latitude": 28.5085,
        "longitude": 77.1565,
        "phone": "011-46300000",
        "emergency_phone": "011-46300001",
        "beds_total": 290,
        "beds_icu": 65,
        "beds_icu_available": 9,
        "beds_emergency": 30,
        "beds_general": 195,
        "is_trauma_center": False,
        "is_pmjay_empanelled": True,
        "accreditation": "NABH",
        "established_year": 2009,
        "total_doctors": 180,
        "description": "Dedicated autonomous government mono-specialty institute specializing exclusively in hepatology, liver transplant, and nephrology.",
    },
]

# --------------------------------------------------
# 35+ PMJAY 2.2 Aligned Procedures
# --------------------------------------------------
PROCEDURES_SEED = [
    # ── Cardiac Specialties ──
    {
        "name": "Coronary Artery Bypass Graft (CABG)",
        "name_hindi": "हृदय बाईपास सर्जरी",
        "category": "cardiac",
        "icd10_code": "I25.1",
        "pmjay_hbp_code": "HBP_CARD_001",
        "pmjay_cost_min": 140000,
        "pmjay_cost_max": 380000,
        "search_aliases": ["bypass surgery", "cabg", "heart bypass", "dil ka operation", "open heart surgery"],
        "is_surgical": True,
        "typical_duration_days": 8,
    },
    {
        "name": "Coronary Angioplasty with Drug-Eluting Stent",
        "name_hindi": "कोरोनरी एंजियोप्लास्टी",
        "category": "cardiac",
        "icd10_code": "I21.9",
        "pmjay_hbp_code": "HBP_CARD_005",
        "pmjay_cost_min": 65000,
        "pmjay_cost_max": 180000,
        "search_aliases": ["angioplasty", "stent", "heart stent", "coronary stent", "blocked artery"],
        "is_surgical": True,
        "typical_duration_days": 2,
    },
    {
        "name": "Permanent Pacemaker Implantation (Dual Chamber)",
        "name_hindi": "पेसमेकर इम्प्लांट",
        "category": "cardiac",
        "icd10_code": "Z95.0",
        "pmjay_hbp_code": "HBP_CARD_008",
        "pmjay_cost_min": 85000,
        "pmjay_cost_max": 220000,
        "search_aliases": ["pacemaker", "heart beat machine", "dil ki dharkan"],
        "is_surgical": True,
        "typical_duration_days": 2,
    },
    {
        "name": "Heart Valve Replacement (Aortic / Mitral)",
        "name_hindi": "हार्ट वाल्व रिप्लेसमेंट",
        "category": "cardiac",
        "icd10_code": "I35.0",
        "pmjay_hbp_code": "HBP_CARD_012",
        "pmjay_cost_min": 170000,
        "pmjay_cost_max": 420000,
        "search_aliases": ["valve surgery", "tavr", "mitral valve", "aortic valve"],
        "is_surgical": True,
        "typical_duration_days": 10,
    },
    {
        "name": "Pediatric Congenital Heart Defect Closure (ASD/VSD)",
        "name_hindi": "दिल के छेद का ऑपरेशन",
        "category": "cardiac",
        "icd10_code": "Q21.0",
        "pmjay_hbp_code": "HBP_CARD_020",
        "pmjay_cost_min": 90000,
        "pmjay_cost_max": 250000,
        "search_aliases": ["hole in heart", "asd closure", "vsd closure", "dil mein chhed"],
        "is_surgical": True,
        "typical_duration_days": 5,
    },

    # ── Orthopedics & Spine ──
    {
        "name": "Total Knee Replacement (TKR - Unilateral)",
        "name_hindi": "घुटना प्रत्यारोपण",
        "category": "orthopedic",
        "icd10_code": "M17.1",
        "pmjay_hbp_code": "HBP_ORTHO_001",
        "pmjay_cost_min": 80000,
        "pmjay_cost_max": 185000,
        "search_aliases": ["knee replacement", "tkr", "knee surgery", "ghutne ka operation", "knee joint replacement"],
        "is_surgical": True,
        "typical_duration_days": 4,
    },
    {
        "name": "Total Hip Replacement (THR - Unilateral)",
        "name_hindi": "कूल्हा प्रत्यारोपण",
        "category": "orthopedic",
        "icd10_code": "M16.1",
        "pmjay_hbp_code": "HBP_ORTHO_002",
        "pmjay_cost_min": 95000,
        "pmjay_cost_max": 210000,
        "search_aliases": ["hip replacement", "thr", "hip surgery", "kadhe ka operation"],
        "is_surgical": True,
        "typical_duration_days": 5,
    },
    {
        "name": "Arthroscopic ACL Ligament Reconstruction",
        "name_hindi": "एसीएल लिगामेंट सर्जरी",
        "category": "orthopedic",
        "icd10_code": "M23.6",
        "pmjay_hbp_code": "HBP_ORTHO_008",
        "pmjay_cost_min": 45000,
        "pmjay_cost_max": 120000,
        "search_aliases": ["acl reconstruction", "ligament tear", "sports injury knee"],
        "is_surgical": True,
        "typical_duration_days": 2,
    },
    {
        "name": "Lumbar Spine Decompression & Microdiscectomy",
        "name_hindi": "रीढ़ की हड्डी का ऑपरेशन",
        "category": "orthopedic",
        "icd10_code": "M51.2",
        "pmjay_hbp_code": "HBP_NEURO_004",
        "pmjay_cost_min": 75000,
        "pmjay_cost_max": 200000,
        "search_aliases": ["slip disc", "sciatica surgery", "spine decompression", "back surgery"],
        "is_surgical": True,
        "typical_duration_days": 3,
    },

    # ── Nephrology & Urology ──
    {
        "name": "Hemodialysis (per session)",
        "name_hindi": "हेमोडायलिसिस",
        "category": "renal",
        "icd10_code": "Z99.2",
        "pmjay_hbp_code": "HBP_RENAL_001",
        "pmjay_cost_min": 1200,
        "pmjay_cost_max": 3500,
        "search_aliases": ["dialysis", "kidney dialysis", "gurdey ki safai", "blood purification"],
        "is_surgical": False,
        "typical_duration_days": 0,
    },
    {
        "name": "Renal Kidney Transplant",
        "name_hindi": "गुर्दा प्रत्यारोपण",
        "category": "renal",
        "icd10_code": "T86.1",
        "pmjay_hbp_code": "HBP_RENAL_010",
        "pmjay_cost_min": 250000,
        "pmjay_cost_max": 650000,
        "search_aliases": ["kidney transplant", "renal transplant", "gurdey ka transplant"],
        "is_surgical": True,
        "typical_duration_days": 12,
    },
    {
        "name": "Arteriovenous (AV) Fistula Construction",
        "name_hindi": "एवी फिस्टुला सर्जरी",
        "category": "renal",
        "icd10_code": "I77.0",
        "pmjay_hbp_code": "HBP_RENAL_003",
        "pmjay_cost_min": 12000,
        "pmjay_cost_max": 35000,
        "search_aliases": ["av fistula", "fistula for dialysis", "fistula operation"],
        "is_surgical": True,
        "typical_duration_days": 1,
    },
    {
        "name": "Transurethral Resection of Prostate (TURP)",
        "name_hindi": "प्रोस्टेट ग्रंथि ऑपरेशन",
        "category": "renal",
        "icd10_code": "N40",
        "pmjay_hbp_code": "HBP_UROL_002",
        "pmjay_cost_min": 30000,
        "pmjay_cost_max": 85000,
        "search_aliases": ["turp", "prostate surgery", "bph surgery"],
        "is_surgical": True,
        "typical_duration_days": 3,
    },

    # ── Neurology & Neurosurgery ──
    {
        "name": "Brain Tumor Craniotomy & Excision",
        "name_hindi": "ब्रेन ट्यूमर ऑपरेशन",
        "category": "neurological",
        "icd10_code": "C71.9",
        "pmjay_hbp_code": "HBP_NEURO_001",
        "pmjay_cost_min": 120000,
        "pmjay_cost_max": 350000,
        "search_aliases": ["brain tumor", "craniotomy", "brain surgery", "dimaag ka operation"],
        "is_surgical": True,
        "typical_duration_days": 7,
    },
    {
        "name": "Acute Ischemic Stroke Mechanical Thrombectomy",
        "name_hindi": "स्ट्रोक क्लॉट रिमूवल",
        "category": "neurological",
        "icd10_code": "I63.9",
        "pmjay_hbp_code": "HBP_NEURO_009",
        "pmjay_cost_min": 150000,
        "pmjay_cost_max": 380000,
        "search_aliases": ["stroke clot removal", "thrombectomy", "brain stroke emergency", "paralysis attack"],
        "is_surgical": True,
        "typical_duration_days": 5,
    },

    # ── Oncology ──
    {
        "name": "Systemic Chemotherapy (per infusion cycle)",
        "name_hindi": "कीमोथेरेपी",
        "category": "oncology",
        "icd10_code": "Z51.1",
        "pmjay_hbp_code": "HBP_ONCOL_001",
        "pmjay_cost_min": 12000,
        "pmjay_cost_max": 85000,
        "search_aliases": ["chemotherapy", "chemo", "cancer treatment", "cancer ki dawa"],
        "is_surgical": False,
        "typical_duration_days": 1,
    },
    {
        "name": "Radiation Therapy (IMRT / VMAT Complete Course)",
        "name_hindi": "रेडिएशन थेरेपी",
        "category": "oncology",
        "icd10_code": "Z51.0",
        "pmjay_hbp_code": "HBP_ONCOL_005",
        "pmjay_cost_min": 75000,
        "pmjay_cost_max": 240000,
        "search_aliases": ["radiation", "radiotherapy", "cancer sekai", "imrt"],
        "is_surgical": False,
        "typical_duration_days": 25,
    },
    {
        "name": "Modified Radical Mastectomy (Breast Cancer)",
        "name_hindi": "स्तन कैंसर सर्जरी",
        "category": "oncology",
        "icd10_code": "C50.9",
        "pmjay_hbp_code": "HBP_ONCOL_011",
        "pmjay_cost_min": 40000,
        "pmjay_cost_max": 130000,
        "search_aliases": ["mastectomy", "breast cancer surgery", "breast tumor"],
        "is_surgical": True,
        "typical_duration_days": 3,
    },
    {
        "name": "Allogeneic Bone Marrow Transplant",
        "name_hindi": "अस्थि मज्जा प्रत्यारोपण",
        "category": "oncology",
        "icd10_code": "Z94.81",
        "pmjay_hbp_code": "HBP_ONCOL_025",
        "pmjay_cost_min": 600000,
        "pmjay_cost_max": 1800000,
        "search_aliases": ["bmt", "bone marrow transplant", "leukemia transplant"],
        "is_surgical": True,
        "typical_duration_days": 30,
    },

    # ── Gastroenterology & Abdominal Surgery ──
    {
        "name": "Laparoscopic Cholecystectomy (Gallbladder Stones)",
        "name_hindi": "पित्ताशय की पथरी का ऑपरेशन",
        "category": "general",
        "icd10_code": "K80.2",
        "pmjay_hbp_code": "HBP_SURG_002",
        "pmjay_cost_min": 25000,
        "pmjay_cost_max": 75000,
        "search_aliases": ["gallbladder stone", "lap chole", "pitte ki pathri"],
        "is_surgical": True,
        "typical_duration_days": 2,
    },
    {
        "name": "Laparoscopic Appendectomy",
        "name_hindi": "अपेंडिक्स ऑपरेशन",
        "category": "general",
        "icd10_code": "K37",
        "pmjay_hbp_code": "HBP_SURG_001",
        "pmjay_cost_min": 22000,
        "pmjay_cost_max": 65000,
        "search_aliases": ["appendix", "appendectomy", "acute appendicitis"],
        "is_surgical": True,
        "typical_duration_days": 2,
    },
    {
        "name": "Endoscopic Retrograde Cholangiopancreatography (ERCP)",
        "name_hindi": "ईआरसीपी पित्त नली जांच",
        "category": "general",
        "icd10_code": "K83.1",
        "pmjay_hbp_code": "HBP_GI_004",
        "pmjay_cost_min": 28000,
        "pmjay_cost_max": 75000,
        "search_aliases": ["ercp", "bile duct stone", "jaundice endoscopy"],
        "is_surgical": True,
        "typical_duration_days": 1,
    },
    {
        "name": "Living Donor Liver Transplant",
        "name_hindi": "लिवर ट्रांसप्लांट",
        "category": "general",
        "icd10_code": "T86.4",
        "pmjay_hbp_code": "HBP_GI_015",
        "pmjay_cost_min": 1400000,
        "pmjay_cost_max": 2800000,
        "search_aliases": ["liver transplant", "cirrhosis surgery", "liver failure"],
        "is_surgical": True,
        "typical_duration_days": 21,
    },

    # ── Ophthalmology ──
    {
        "name": "Cataract Surgery (Phaco + Foldable IOL)",
        "name_hindi": "मोतियाबिंद फेको ऑपरेशन",
        "category": "ophthalmology",
        "icd10_code": "H26.9",
        "pmjay_hbp_code": "HBP_OPHTHAL_001",
        "pmjay_cost_min": 8500,
        "pmjay_cost_max": 38000,
        "search_aliases": ["cataract", "cataract surgery", "motiyabind", "motia", "eye surgery", "aankh ka operation"],
        "is_surgical": True,
        "typical_duration_days": 1,
    },
    {
        "name": "Pars Plana Vitrectomy (Retinal Detachment)",
        "name_hindi": "रेटिना ऑपरेशन",
        "category": "ophthalmology",
        "icd10_code": "H33.0",
        "pmjay_hbp_code": "HBP_OPHTHAL_006",
        "pmjay_cost_min": 35000,
        "pmjay_cost_max": 95000,
        "search_aliases": ["vitrectomy", "retina surgery", "parda fatna"],
        "is_surgical": True,
        "typical_duration_days": 1,
    },

    # ── Obstetrics & Gynecology ──
    {
        "name": "Normal Vaginal Delivery",
        "name_hindi": "सामान्य प्रसव",
        "category": "gynecology",
        "icd10_code": "O80",
        "pmjay_hbp_code": "HBP_GYNEC_001",
        "pmjay_cost_min": 6000,
        "pmjay_cost_max": 28000,
        "search_aliases": ["normal delivery", "delivery", "baby delivery", "prasav"],
        "is_surgical": False,
        "typical_duration_days": 2,
    },
    {
        "name": "Caesarean Section Delivery (LSCS)",
        "name_hindi": "सिजेरियन ऑपरेशन प्रसव",
        "category": "gynecology",
        "icd10_code": "O82",
        "pmjay_hbp_code": "HBP_GYNEC_002",
        "pmjay_cost_min": 18000,
        "pmjay_cost_max": 65000,
        "search_aliases": ["c section", "caesarean", "csection", "operation delivery"],
        "is_surgical": True,
        "typical_duration_days": 4,
    },
    {
        "name": "Total Laparoscopic Hysterectomy (TLH)",
        "name_hindi": "बच्चेदानी निकालने का ऑपरेशन",
        "category": "gynecology",
        "icd10_code": "N85.9",
        "pmjay_hbp_code": "HBP_GYNEC_007",
        "pmjay_cost_min": 35000,
        "pmjay_cost_max": 110000,
        "search_aliases": ["hysterectomy", "uterus removal", "bachhedani operation"],
        "is_surgical": True,
        "typical_duration_days": 3,
    },

    # ── Critical Care & Diagnostics ──
    {
        "name": "ICU Ventilator Life Support (per day)",
        "name_hindi": "आईसीयू वेंटिलेटर सेवा (प्रति दिन)",
        "category": "critical_care",
        "icd10_code": "Z99.11",
        "pmjay_hbp_code": "HBP_ICU_001",
        "pmjay_cost_min": 6000,
        "pmjay_cost_max": 25000,
        "search_aliases": ["icu bed", "ventilator", "critical care", "oxygen bed"],
        "is_surgical": False,
        "typical_duration_days": 1,
    },
    {
        "name": "Neonatal Intensive Care (NICU Level 3 - per day)",
        "name_hindi": "एनआईसीयू नवजात शिशु देखभाल (प्रति दिन)",
        "category": "pediatric",
        "icd10_code": "P07.3",
        "pmjay_hbp_code": "HBP_NICU_002",
        "pmjay_cost_min": 4500,
        "pmjay_cost_max": 18000,
        "search_aliases": ["nicu", "premature baby incubator", "nursery icu"],
        "is_surgical": False,
        "typical_duration_days": 1,
    },
    {
        "name": "Whole Body 18F-FDG PET-CT Scan",
        "name_hindi": "होल बॉडी पीईटी-सीटी स्कैन",
        "category": "diagnostic",
        "icd10_code": "Z01.8",
        "pmjay_hbp_code": "HBP_DIAG_003",
        "pmjay_cost_min": 12000,
        "pmjay_cost_max": 28000,
        "search_aliases": ["pet scan", "pet ct", "cancer scan"],
        "is_surgical": False,
        "typical_duration_days": 0,
    },
    {
        "name": "High-Field 3.0 Tesla Brain MRI with Contrast",
        "name_hindi": "3.0 टेस्ला ब्रेन एमआरआई स्कैन",
        "category": "diagnostic",
        "icd10_code": "Z01.8",
        "pmjay_hbp_code": None,
        "pmjay_cost_min": 4500,
        "pmjay_cost_max": 12500,
        "search_aliases": ["mri brain", "mri scan", "head mri"],
        "is_surgical": False,
        "typical_duration_days": 0,
    },
]


async def seed_hospitals():
    """
    Main seed function — called on startup if SEED_ON_STARTUP=True.
    Idempotent: skips if hospitals already exist.
    """
    from app.database import async_session_factory
    from app.models.hospital import Hospital, HospitalType, DataSourceLabel
    from app.models.procedure import Procedure
    from app.models.hospital_procedure import HospitalProcedure
    from app.models.facility import Facility, FacilityCategory
    from app.models.department import Department
    from app.models.data_source import DataSource, DataSourceType
    from app.models.user import User, UserRole
    from app.services.auth_service import hash_password
    from geoalchemy2.shape import from_shape
    try:
        from slugify import slugify
    except ImportError:
        try:
            from python_slugify import slugify
        except ImportError:
            def slugify(text: str) -> str:
                import re
                return re.sub(r'[\W_]+', '-', text.lower()).strip('-')

    async with async_session_factory() as db:
        existing = (await db.execute(select(Hospital).limit(1))).scalar_one_or_none()
        if existing:
            logger.info("Database already seeded, skipping")
            return

        logger.info("Seeding database with comprehensive hospital and procedure registry...")

        # Create seed data source record
        data_source = DataSource(
            name="Med Route Clinical Registry v2.0",
            source_type=DataSourceType.SEED_SCRIPT,
            description="Comprehensive hospital, ICU telemetry, and PMJAY package dataset for North India.",
            record_count=len(HOSPITALS_DATA),
        )
        db.add(data_source)
        await db.flush()

        # Seed procedures
        procedures = []
        for proc_data in PROCEDURES_SEED:
            proc = Procedure(
                name=proc_data["name"],
                name_hindi=proc_data.get("name_hindi"),
                category=proc_data["category"],
                icd10_code=proc_data.get("icd10_code"),
                pmjay_hbp_code=proc_data.get("pmjay_hbp_code"),
                pmjay_cost_min=proc_data.get("pmjay_cost_min"),
                pmjay_cost_max=proc_data.get("pmjay_cost_max"),
                search_aliases=proc_data.get("search_aliases", []),
                is_surgical=proc_data.get("is_surgical", False),
                typical_duration_days=proc_data.get("typical_duration_days", 1),
            )
            db.add(proc)
            procedures.append(proc)
        await db.flush()

        # Seed hospitals
        hospitals = []
        for h_data in HOSPITALS_DATA:
            location = from_shape(
                Point(h_data["longitude"], h_data["latitude"]), srid=4326
            )
            slug = slugify(f"{h_data['name']} {h_data['city']}")

            hospital = Hospital(
                name=h_data["name"],
                slug=slug,
                type=HospitalType(h_data["type"]),
                address=h_data["address"],
                city=h_data["city"],
                state=h_data["state"],
                pincode=h_data["pincode"],
                latitude=h_data["latitude"],
                longitude=h_data["longitude"],
                location=location,
                phone=h_data["phone"],
                emergency_phone=h_data.get("emergency_phone"),
                beds_total=h_data.get("beds_total", 100),
                beds_icu=h_data.get("beds_icu", 10),
                beds_icu_available=h_data.get("beds_icu_available", 5),
                beds_emergency=h_data.get("beds_emergency", 20),
                beds_general=h_data.get("beds_general", 70),
                is_trauma_center=h_data.get("is_trauma_center", False),
                is_pmjay_empanelled=h_data.get("is_pmjay_empanelled", False),
                accreditation=h_data.get("accreditation"),
                established_year=h_data.get("established_year"),
                total_doctors=h_data.get("total_doctors"),
                description=h_data.get("description"),
                overall_rating=round(random.uniform(4.0, 4.9), 1),
                total_reviews=random.randint(120, 2400),
                verified=True,
                data_source_label=DataSourceLabel.SIMULATED,
                data_source_id=data_source.id,
                is_active=True,
            )
            db.add(hospital)
            hospitals.append(hospital)
        await db.flush()

        # Link each hospital with 8-18 relevant procedures
        for hospital in hospitals:
            num_procedures = random.randint(8, min(18, len(procedures)))
            selected_procs = random.sample(procedures, num_procedures)

            for proc in selected_procs:
                if proc.pmjay_cost_min and proc.pmjay_cost_max:
                    is_govt = hospital.type == HospitalType.GOVERNMENT
                    multiplier = 0.5 if is_govt else random.uniform(0.9, 1.3)
                    cost_min = int(proc.pmjay_cost_min * multiplier)
                    cost_max = int(proc.pmjay_cost_max * multiplier)
                else:
                    cost_min = None
                    cost_max = None

                hp = HospitalProcedure(
                    hospital_id=hospital.id,
                    procedure_id=proc.id,
                    cost_min=cost_min,
                    cost_max=cost_max,
                    cost_avg=int((cost_min + cost_max) / 2) if cost_min and cost_max else None,
                    pmjay_covered=hospital.is_pmjay_empanelled and proc.pmjay_hbp_code is not None,
                    pmjay_package_rate=proc.pmjay_cost_min if hospital.is_pmjay_empanelled else None,
                    success_rate=round(random.uniform(91.0, 99.4), 1),
                    volume_per_year=random.randint(80, 2200),
                    is_available=True,
                    data_source_label=DataSourceLabel.SIMULATED,
                )
                db.add(hp)

        # Add facilities per hospital
        facilities_template = [
            ("Advanced ICU / CCU", FacilityCategory.ICU, True),
            ("Licensed Blood Bank", FacilityCategory.LABORATORY, True),
            ("3.0 Tesla MRI", FacilityCategory.IMAGING, True),
            ("128-Slice Dual Source CT", FacilityCategory.IMAGING, True),
            ("Modular Laminar Operation Theatres", FacilityCategory.SURGERY, True),
            ("Level 1 / 2 Trauma Resuscitation", FacilityCategory.EMERGENCY, True),
            ("24x7 In-House Pharmacy", FacilityCategory.PHARMACY, True),
            ("Hemodialysis Wing", FacilityCategory.THERAPY, True),
            ("Level 3 NICU / PICU", FacilityCategory.ICU, False),
            ("Biplane Cardiac Cath Lab", FacilityCategory.SURGERY, False),
            ("PET-CT Whole Body Scanner", FacilityCategory.IMAGING, False),
            ("ACLS Ambulance Fleet", FacilityCategory.EMERGENCY, True),
        ]

        for hospital in hospitals:
            for fname, fcat, is_common in facilities_template:
                if is_common or random.random() > 0.4:
                    fac = Facility(
                        hospital_id=hospital.id,
                        name=fname,
                        category=fcat,
                        is_available=True,
                        is_24x7=(fcat in [FacilityCategory.ICU, FacilityCategory.EMERGENCY]),
                    )
                    db.add(fac)

        # Seed admin and citizen users
        admin = User(
            name="Med Route Registry Admin",
            email="admin@medroute.in",
            phone="9999999999",
            password_hash=hash_password("Admin@MedRoute2024"),
            role=UserRole.ADMIN,
            is_active=True,
        )
        db.add(admin)

        citizen = User(
            name="Ramesh Sharma",
            email="patient@medroute.in",
            phone="9876543210",
            password_hash=hash_password("Patient@MedRoute2024"),
            role=UserRole.CITIZEN,
            city="Mohali",
            latitude=30.7046,
            longitude=76.7179,
            is_active=True,
        )
        db.add(citizen)

        await db.commit()
        logger.info(
            "✅ Seed data committed successfully",
            hospitals=len(hospitals),
            procedures=len(procedures),
        )


if __name__ == "__main__":
    asyncio.run(seed_hospitals())
