import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "border-subtle": "#E2E8F0",
        "brand-blue-interactive": "#1778F2",
        "primary": "#000000",
        "background": "#faf8ff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-error-container": "#93000a",
        "tertiary-container": "#410001",
        "inverse-surface": "#283044",
        "on-tertiary-container": "#e65040",
        "on-tertiary-fixed-variant": "#900e0b",
        "surface-card": "#FFFFFF",
        "surface-container-high": "#e2e7ff",
        "on-secondary-fixed-variant": "#004d62",
        "on-background": "#131b2e",
        "tertiary-fixed-dim": "#ffb4a9",
        "surface-ice": "#F0F7FF",
        "error": "#ba1a1a",
        "outline-variant": "#c7c5d1",
        "primary-fixed-dim": "#bec2ff",
        "on-surface": "#131b2e",
        "on-tertiary-fixed": "#410001",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#81d1f0",
        "inverse-primary": "#bec2ff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3b4180",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "secondary-fixed": "#b9eaff",
        "surface-container-highest": "#dae2fd",
        "primary-fixed": "#e0e0ff",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "tertiary": "#000000",
        "badge-rating": "#F59E0B",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#001f29",
        "surface-tint": "#53599a",
        "secondary-container": "#8fdfff",
        "surface-canvas": "#F8FAFC",
        "on-secondary-container": "#00647d",
        "primary-container": "#0c1253",
        "on-primary-container": "#787ec2",
        "outline": "#777681",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdad5",
        "secondary": "#006781",
        "on-surface-variant": "#464650",
        "surface-variant": "#dae2fd",
        "badge-cashless": "#0D9488",
        "surface": "#faf8ff",
        "on-primary-fixed": "#0c1253",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-md": "1rem",
        margin: "1.5rem",
        "gutter-sm": "1rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "gutter-lg": "2rem",
        "space-sm": "0.5rem",
        "margin-sm": "1rem",
        "margin-lg": "4rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        sans: ["Hanken Grotesk", "sans-serif"],
        heading: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["1.375rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "headline-xl": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
