import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "background": "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container": "#eaedff",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#88b9e3",
        "surface-variant": "#dae2fd",
        "on-secondary-fixed-variant": "#005049",
        "surface-container-low": "#f2f3ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "primary-container": "#0c4a6e",
        "surface": "#faf8ff",
        "secondary-container": "#86f2e4",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-tertiary-container": "#ff969c",
        "tertiary-fixed": "#ffdada",
        "outline-variant": "#c1c7cf",
        "on-primary-fixed": "#001e30",
        "on-primary-fixed-variant": "#0e4b6f",
        "on-secondary-container": "#006f66",
        "on-tertiary-fixed": "#40000c",
        "secondary": "#006a61",
        "on-error": "#ffffff",
        "tertiary": "#660019",
        "outline": "#72787f",
        "inverse-primary": "#9bccf6",
        "primary-fixed": "#cbe6ff",
        "primary": "#00334f",
        "surface-tint": "#2f6388",
        "on-surface-variant": "#41474e",
        "on-background": "#131b2e",
        "on-surface": "#131b2e",
        "tertiary-container": "#900027",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#920028",
        "error": "#ba1a1a",
        "secondary-fixed": "#89f5e7",
        "inverse-surface": "#283044",
        "on-secondary-fixed": "#00201d",
        "primary-fixed-dim": "#9bccf6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        gutter: "1.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "gutter-sm": "1rem",
        margin: "2rem",
      },
      fontFamily: {
        "metric-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "metric-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "metric-xl": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "metric-md": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
